name: xdg_icons_example
description: XDG icons example
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

platforms:
  linux:

dependencies:
  flutter:
    sdk: flutter
  xdg_icons:
    path: ../
  yaru: ^0.3.3

flutter:
  uses-material-design: true
