name: ubuntu_flavor
description: Detect Ubuntu flavor
homepage: https://github.com/ubuntu-flutter-community/ubuntu_flavor
repository: https://github.com/ubuntu-flutter-community/ubuntu_flavor
issue_tracker: https://github.com/ubuntu-flutter-community/ubuntu_flavor/issues
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
