name: wizard_router
description: >-
  Routing for linear wizards. No dependencies between pages. Pages merely
  request the next page. Routes and conditions defined in a central place.
homepage: https://github.com/ubuntu-flutter-community/wizard_router
repository: https://github.com/ubuntu-flutter-community/wizard_router
issue_tracker: https://github.com/ubuntu-flutter-community/wizard_router/issues
version: 1.0.2

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  collection: ^1.15.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  safe_change_notifier: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
