name: xdg_icons
description: XDG theme icons for Flutter.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/xdg_icons
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.0.5

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.1"

platforms:
  linux:

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  mocktail: ^1.0.0
  path: ^1.8.3
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.4.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: XdgIconsPlugin
