name: xdg_icons
description: XDG theme icons for Flutter.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/xdg_icons
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.0.2

environment:
  sdk: '<4.0.0'
  flutter: '>=3.0.0'

platforms:
  linux:

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  mocktail: ^1.0.0
  path: ^1.8.0
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: XdgIconsPlugin
