name: ubuntu_widgets
description: |
  A collection of widgets developed for Flutter-based Ubuntu applications.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_widgets
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.1.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  collection: ^1.16.0
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  password_strength: ^0.2.0
  ubuntu_localizations: ^0.3.0
  yaru: ^0.9.0
  yaru_icons: ^2.0.0
  yaru_widgets: ^2.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  yaru_test: ^0.1.1
