name: ubuntu_widgets
description: |
  A collection of widgets developed for Flutter-based Ubuntu applications.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_widgets
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.5.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  collection: ^1.17.0
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  password_strength: ^0.2.0
  ubuntu_localizations: ^0.3.5
  yaru: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.3.0
  yaru_test: ^0.1.5
