name: ubuntu_widgets
description: |
  A collection of widgets developed for Flutter-based Ubuntu applications.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  collection: ^1.16.0
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  password_strength: ^0.2.0
  ubuntu_localizations: ^0.2.0
  yaru: ^0.9.0
  yaru_icons: ^1.0.3
  yaru_widgets: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  yaru_test: ^0.1.1
