name: ubuntu_flavor
description: Detect Ubuntu flavor
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_flavor
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.3.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.11.0
  platform_linux: ^0.1.2

dev_dependencies:
  test: ^1.21.1
  ubuntu_lints: ^0.3.0
