name: ubuntu_logger
description: A logging frontend based on Google's logging library for Dart.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_logger
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  logging: '>=1.0.1 <1.2.0'
  logging_appenders: ^1.0.0
  path: ^1.9.0

dev_dependencies:
  ubuntu_lints: ^0.4.1
