name: wizard_router
description: >-
  Routing for linear wizards. No dependencies between pages. Pages merely
  request the next page. Routes and conditions defined in a central place.
homepage: https://github.com/jpnurmi/wizard_router
repository: https://github.com/jpnurmi/wizard_router
issue_tracker: https://github.com/jpnurmi/wizard_router/issues
version: 0.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flow_builder: ^0.0.3
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
