name: wizard_router
description: >-
  Routing for linear wizards. No dependencies between pages. Pages merely
  request the next page. Routes and conditions defined in a central place.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/wizard_router
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 1.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  collection: ^1.17.0
  flow_builder: ^0.0.10
  flutter:
    sdk: flutter
  safe_change_notifier: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.3.0
