name: ubuntu_localizations
description: Provides extra localizations for Ubuntu applications.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_localizations
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.4.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.22.1"

dependencies:
  collection: ^1.17.0
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.3.1
  xml: ^6.1.0
