name: ubuntu_localizations
description: Common localizations for Ubuntu applications.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  collection: ^1.15.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  xml: ^5.3.1
