name: ubuntu_localizations
description: Provides extra localizations for Ubuntu applications.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_localizations
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.0.2

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  collection: ^1.15.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  xml: ^6.1.0
