name: ubuntu_test
description: Provides test extensions for Ubuntu applications.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_test
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.1.0-beta.11

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.1
  flutter_markdown: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_test:
    sdk: flutter
  matcher: ^0.12.16
  mockito: ^5.4.0
  ubuntu_localizations: ^0.4.1
  yaru_test: ^0.1.5

dev_dependencies:
  ubuntu_lints: ^0.4.0

flutter:
  assets:
    - assets/
