name: xdg_icons_example
description: XDG icons example
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.35.3"

platforms:
  linux:

dependencies:
  flutter:
    sdk: flutter
  xdg_icons: ^0.1.2
  yaru: ^9.0.0

flutter:
  uses-material-design: true
