name: ubuntu_service
description: Simple service locator API based on GetIt.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_service
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.3.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  get_it: ^7.4.1
  meta: ^1.7.0

dev_dependencies:
  test: ^1.21.1
  ubuntu_lints: ^0.2.0
