name: platform_linux
description: |
  Linux-specific extensions on the platform package for detecting Linux distro
  and desktop environment.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/platform_linux
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  platform: ^3.1.0

dev_dependencies:
  mockito: ^5.4.2
  test: ^1.21.0
  ubuntu_lints: ^0.2.0
