name: safe_change_notifier
description: |
  A safe drop-in replacement for Flutter's ChangeNotifier, that makes
  notifyListeners() a no-op, rather than an error, after its disposal.
homepage: https://github.com/canonical/ubuntu-flutter-plugins
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/safe_change_notifier
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  state_notifier: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.2.0
