name: Analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  analyzer:
    runs-on: ubuntu-20.04
    container:
      image: dart:stable
    steps:
      - uses: actions/checkout@v3
      - run: dart pub get
      - run: dart analyze --fatal-infos .

  format:
    runs-on: ubuntu-20.04
    container:
      image: dart:stable
    steps:
      - uses: actions/checkout@v3
      - run: dart pub get
      - run: dart format --set-exit-if-changed .

  pub:
    runs-on: ubuntu-20.04
    container:
      image: dart:stable
    steps:
      - uses: actions/checkout@v3
      - run: dart pub get
      - run: dart pub publish --dry-run
